version: '3'
services:
  backend:
    image: 571152876653.dkr.ecr.sa-east-1.amazonaws.com/meridian:1.0
    ports:
      - "3030:3030"
    restart: always

    platform: linux/amd64
    volumes:
      - ./backend:/usr/src/app 
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.0
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db

  caddy:
    image: caddy:2.4.5
    restart: always
    ports:
      - "8080:80"

volumes:
  postgres_data:
    driver: local
